### ISSUE TITLE
README.md file missing

### ISSUE THREAD

**Issue by ragnarlodbrok1992** [RaminNietzsche/trex#1]
Hi,

I'm trying to install this package using pip3.4 on RHEL 7.3 and I'm getting this error from setup.py:
Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-nm7mrv__/trex-api/setup.py", line 53, in <module>

        long_description=read_md('README.md'),

      File "/tmp/pip-build-nm7mrv__/trex-api/setup.py", line 26, in <lambda>

        read_md = lambda f: open(f, 'r').read()

    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

Any help would be greatly appreciated.

**Comment by jensfr** [comment]
I have the same problem

**Comment by lb1wh** [comment]
Same here. Not so sure that this is mean to work on Python 3. The setup.py says it's written for Python27.
